spring:
  application:
    name: shortlink
  datasource:
    url: jdbc:h2:mem:shortlinkdb
    driver-class-name: org.h2.Driver
    username: root
    password: password
  jpa:
    show-sql: true
  flyway:
    enabled: true