spring:
  application:
    name: shortlink
  datasource:
    url: jdbc:mysql://localhost:3306/shortlinkdb?createDatabaseIfNotExist=true
    username: root
    password: wannabe4
  jpa:
    show-sql: true
app-url: http://localhost:8080/