spring:
  application:
    name: shortlink
  datasource:
    url: jdbc:mysql://localhost:3306/shortlinkdb?createDatabaseIfNotExist=true
    username: root
    password: wannabe4
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15m
    refreshTokenExpiration: 604800 # 7d
app-url: http://localhost:8080/